spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/followme
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  kafka:
    bootstrap-servers: 172.31.10.105:9092,172.31.1.110:9092,172.31.15.248:9092
    properties:
      security.protocol: SSL
      ssl.truststore.location: /etc/kafka/ssl/kafka.server.truststore.jks
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
      ssl.endpoint.identification.algorithm: ""

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
